**ID - 2215151038**

**Name - Musber Ahmed Sadman**

**Sec - 7A2**

Course Code - CSE 413

Course Name - Simulation and Modeling Lab


In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# A 3x3 matrix was generated
# Run the code twice
matrix1 = np.random.randint(1, 51, size=(3, 3))
print("The Matrix:\n",matrix1)

The Matrix:
 [[14 46 39]
 [17 50 12]
 [ 5 11  4]]


In [17]:
# With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.
np.random.seed(10)
matrix2 = np.random.randint(1, 51, size=(3, 3))
print("The Matrix:\n",matrix2)

The Matrix:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [21]:
# Without setting a seed, allowing random values to change each time.
np.random.seed(None)
matrix3 = np.random.randint(1, 51, size=(3, 3))
print("The Matrix:\n",matrix3)

The Matrix:
 [[50  4 11]
 [14 12 12]
 [13 48 48]]


# **The difference between the two outputs**


> **First Code:** We can see that, on the first matrix for fixed seed (matrix2), the output comes the same everytime we run the code. The reason is the function "np.random.seed(10)" that ensures that the numbers generated for the first time remains the same.

>**Second Code:** In this case we can see that the "np.random.seed()" was applied but because of "None" in the mentioned function, the code having no seed value generates a random value for the nonseeded matrix (matrix3) everytime we run the code.

**The reason for using "10" as the seed value is that- using the value 10 means any integers i.e. within the range of 0-9 would be used as seed. This ensures that the random values stay same.**


